version: '3.7'

x-logging:
    &default-logging
    driver: "json-file"
    options:
        max-size: "5m"
        max-file: "1"

services:

    php:
        build: '${DOCKERFILE_PHP:-../../skeleton/php}'
        restart: 'unless-stopped'
        networks: [ 'default', 'services' ]
        hostname: '${HOSTNAME}'
        logging: *default-logging
        volumes:
            - source: './srv'
              target: '/srv'
              type: 'bind'
    web:
        build: '${DOCKERFILE_WEB:-../../skeleton/web}'
        restart: 'unless-stopped'
        networks: [ 'default', 'public' ]
        hostname: '${HOSTNAME}'
        logging: *default-logging
        depends_on: [ 'php' ]
        volumes:
            - source: './srv/public'
              target: '/srv/public'
              type: 'bind'
              read_only: true
        labels:
            # See docs at https://docs.traefik.io/configuration/backends/docker/#on-containers
            traefik.enable: false
            traefik.frontend.rule: 'Host: ${HOSTNAME}'

networks:
    default:
        name: '${HOSTNAME}'
        driver_opts:
            com.docker.network.enable_ipv6: 'true'
    services:
        external: true
    public:
        external: true
