version: '3.7'

x-logging:
    &default-logging
    driver: 'json-file'
    options:
        max-size: '5m'
        max-file: '1'

services:

    mysql:
        image: 'srv/mysql'
        build: './images/mysql'
        command: [ '--default-authentication-plugin', 'mysql_native_password' ]
        restart: 'unless-stopped'
        volumes: [ '/var/lib/mysql:/var/lib/mysql' ]
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        logging: *default-logging

networks:
    default:
        name: 'services'
        driver_opts:
            com.docker.network.enable_ipv6: 'true'
